# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/bu/Desktop/Data Science/Quantitatives/HFT_System"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/bu/Desktop/Data Science/Quantitatives/HFT_System"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/bu/Desktop/Data Science/Quantitatives/HFT_System/CMakeFiles" "/Users/bu/Desktop/Data Science/Quantitatives/HFT_System//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/bu/Desktop/Data Science/Quantitatives/HFT_System/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named nanoex

# Build rule for target.
nanoex: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nanoex
.PHONY : nanoex

# fast build rule for target.
nanoex/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanoex.dir/build.make CMakeFiles/nanoex.dir/build
.PHONY : nanoex/fast

#=============================================================================
# Target rules for targets named nanoex_gui

# Build rule for target.
nanoex_gui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nanoex_gui
.PHONY : nanoex_gui

# fast build rule for target.
nanoex_gui/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanoex_gui.dir/build.make CMakeFiles/nanoex_gui.dir/build
.PHONY : nanoex_gui/fast

#=============================================================================
# Target rules for targets named nanoex_autogen_timestamp_deps

# Build rule for target.
nanoex_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nanoex_autogen_timestamp_deps
.PHONY : nanoex_autogen_timestamp_deps

# fast build rule for target.
nanoex_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanoex_autogen_timestamp_deps.dir/build.make CMakeFiles/nanoex_autogen_timestamp_deps.dir/build
.PHONY : nanoex_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named nanoex_autogen

# Build rule for target.
nanoex_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nanoex_autogen
.PHONY : nanoex_autogen

# fast build rule for target.
nanoex_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanoex_autogen.dir/build.make CMakeFiles/nanoex_autogen.dir/build
.PHONY : nanoex_autogen/fast

#=============================================================================
# Target rules for targets named nanoex_gui_autogen_timestamp_deps

# Build rule for target.
nanoex_gui_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nanoex_gui_autogen_timestamp_deps
.PHONY : nanoex_gui_autogen_timestamp_deps

# fast build rule for target.
nanoex_gui_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanoex_gui_autogen_timestamp_deps.dir/build.make CMakeFiles/nanoex_gui_autogen_timestamp_deps.dir/build
.PHONY : nanoex_gui_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named nanoex_gui_autogen

# Build rule for target.
nanoex_gui_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nanoex_gui_autogen
.PHONY : nanoex_gui_autogen

# fast build rule for target.
nanoex_gui_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanoex_gui_autogen.dir/build.make CMakeFiles/nanoex_gui_autogen.dir/build
.PHONY : nanoex_gui_autogen/fast

nanoex_autogen/mocs_compilation.o: nanoex_autogen/mocs_compilation.cpp.o
.PHONY : nanoex_autogen/mocs_compilation.o

# target to build an object file
nanoex_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanoex.dir/build.make CMakeFiles/nanoex.dir/nanoex_autogen/mocs_compilation.cpp.o
.PHONY : nanoex_autogen/mocs_compilation.cpp.o

nanoex_autogen/mocs_compilation.i: nanoex_autogen/mocs_compilation.cpp.i
.PHONY : nanoex_autogen/mocs_compilation.i

# target to preprocess a source file
nanoex_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanoex.dir/build.make CMakeFiles/nanoex.dir/nanoex_autogen/mocs_compilation.cpp.i
.PHONY : nanoex_autogen/mocs_compilation.cpp.i

nanoex_autogen/mocs_compilation.s: nanoex_autogen/mocs_compilation.cpp.s
.PHONY : nanoex_autogen/mocs_compilation.s

# target to generate assembly for a file
nanoex_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanoex.dir/build.make CMakeFiles/nanoex.dir/nanoex_autogen/mocs_compilation.cpp.s
.PHONY : nanoex_autogen/mocs_compilation.cpp.s

nanoex_gui.o: nanoex_gui.cpp.o
.PHONY : nanoex_gui.o

# target to build an object file
nanoex_gui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanoex_gui.dir/build.make CMakeFiles/nanoex_gui.dir/nanoex_gui.cpp.o
.PHONY : nanoex_gui.cpp.o

nanoex_gui.i: nanoex_gui.cpp.i
.PHONY : nanoex_gui.i

# target to preprocess a source file
nanoex_gui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanoex_gui.dir/build.make CMakeFiles/nanoex_gui.dir/nanoex_gui.cpp.i
.PHONY : nanoex_gui.cpp.i

nanoex_gui.s: nanoex_gui.cpp.s
.PHONY : nanoex_gui.s

# target to generate assembly for a file
nanoex_gui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanoex_gui.dir/build.make CMakeFiles/nanoex_gui.dir/nanoex_gui.cpp.s
.PHONY : nanoex_gui.cpp.s

nanoex_gui_autogen/mocs_compilation.o: nanoex_gui_autogen/mocs_compilation.cpp.o
.PHONY : nanoex_gui_autogen/mocs_compilation.o

# target to build an object file
nanoex_gui_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanoex_gui.dir/build.make CMakeFiles/nanoex_gui.dir/nanoex_gui_autogen/mocs_compilation.cpp.o
.PHONY : nanoex_gui_autogen/mocs_compilation.cpp.o

nanoex_gui_autogen/mocs_compilation.i: nanoex_gui_autogen/mocs_compilation.cpp.i
.PHONY : nanoex_gui_autogen/mocs_compilation.i

# target to preprocess a source file
nanoex_gui_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanoex_gui.dir/build.make CMakeFiles/nanoex_gui.dir/nanoex_gui_autogen/mocs_compilation.cpp.i
.PHONY : nanoex_gui_autogen/mocs_compilation.cpp.i

nanoex_gui_autogen/mocs_compilation.s: nanoex_gui_autogen/mocs_compilation.cpp.s
.PHONY : nanoex_gui_autogen/mocs_compilation.s

# target to generate assembly for a file
nanoex_gui_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanoex_gui.dir/build.make CMakeFiles/nanoex_gui.dir/nanoex_gui_autogen/mocs_compilation.cpp.s
.PHONY : nanoex_gui_autogen/mocs_compilation.cpp.s

src/chart_widget.o: src/chart_widget.cpp.o
.PHONY : src/chart_widget.o

# target to build an object file
src/chart_widget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanoex_gui.dir/build.make CMakeFiles/nanoex_gui.dir/src/chart_widget.cpp.o
.PHONY : src/chart_widget.cpp.o

src/chart_widget.i: src/chart_widget.cpp.i
.PHONY : src/chart_widget.i

# target to preprocess a source file
src/chart_widget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanoex_gui.dir/build.make CMakeFiles/nanoex_gui.dir/src/chart_widget.cpp.i
.PHONY : src/chart_widget.cpp.i

src/chart_widget.s: src/chart_widget.cpp.s
.PHONY : src/chart_widget.s

# target to generate assembly for a file
src/chart_widget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanoex_gui.dir/build.make CMakeFiles/nanoex_gui.dir/src/chart_widget.cpp.s
.PHONY : src/chart_widget.cpp.s

src/indicators.o: src/indicators.cpp.o
.PHONY : src/indicators.o

# target to build an object file
src/indicators.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanoex.dir/build.make CMakeFiles/nanoex.dir/src/indicators.cpp.o
.PHONY : src/indicators.cpp.o

src/indicators.i: src/indicators.cpp.i
.PHONY : src/indicators.i

# target to preprocess a source file
src/indicators.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanoex.dir/build.make CMakeFiles/nanoex.dir/src/indicators.cpp.i
.PHONY : src/indicators.cpp.i

src/indicators.s: src/indicators.cpp.s
.PHONY : src/indicators.s

# target to generate assembly for a file
src/indicators.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanoex.dir/build.make CMakeFiles/nanoex.dir/src/indicators.cpp.s
.PHONY : src/indicators.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanoex.dir/build.make CMakeFiles/nanoex.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanoex.dir/build.make CMakeFiles/nanoex.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanoex.dir/build.make CMakeFiles/nanoex.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/market_data.o: src/market_data.cpp.o
.PHONY : src/market_data.o

# target to build an object file
src/market_data.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanoex.dir/build.make CMakeFiles/nanoex.dir/src/market_data.cpp.o
.PHONY : src/market_data.cpp.o

src/market_data.i: src/market_data.cpp.i
.PHONY : src/market_data.i

# target to preprocess a source file
src/market_data.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanoex.dir/build.make CMakeFiles/nanoex.dir/src/market_data.cpp.i
.PHONY : src/market_data.cpp.i

src/market_data.s: src/market_data.cpp.s
.PHONY : src/market_data.s

# target to generate assembly for a file
src/market_data.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanoex.dir/build.make CMakeFiles/nanoex.dir/src/market_data.cpp.s
.PHONY : src/market_data.cpp.s

src/matching_engine.o: src/matching_engine.cpp.o
.PHONY : src/matching_engine.o

# target to build an object file
src/matching_engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanoex.dir/build.make CMakeFiles/nanoex.dir/src/matching_engine.cpp.o
.PHONY : src/matching_engine.cpp.o

src/matching_engine.i: src/matching_engine.cpp.i
.PHONY : src/matching_engine.i

# target to preprocess a source file
src/matching_engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanoex.dir/build.make CMakeFiles/nanoex.dir/src/matching_engine.cpp.i
.PHONY : src/matching_engine.cpp.i

src/matching_engine.s: src/matching_engine.cpp.s
.PHONY : src/matching_engine.s

# target to generate assembly for a file
src/matching_engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanoex.dir/build.make CMakeFiles/nanoex.dir/src/matching_engine.cpp.s
.PHONY : src/matching_engine.cpp.s

src/order_book.o: src/order_book.cpp.o
.PHONY : src/order_book.o

# target to build an object file
src/order_book.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanoex.dir/build.make CMakeFiles/nanoex.dir/src/order_book.cpp.o
.PHONY : src/order_book.cpp.o

src/order_book.i: src/order_book.cpp.i
.PHONY : src/order_book.i

# target to preprocess a source file
src/order_book.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanoex.dir/build.make CMakeFiles/nanoex.dir/src/order_book.cpp.i
.PHONY : src/order_book.cpp.i

src/order_book.s: src/order_book.cpp.s
.PHONY : src/order_book.s

# target to generate assembly for a file
src/order_book.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanoex.dir/build.make CMakeFiles/nanoex.dir/src/order_book.cpp.s
.PHONY : src/order_book.cpp.s

src/performance.o: src/performance.cpp.o
.PHONY : src/performance.o

# target to build an object file
src/performance.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanoex.dir/build.make CMakeFiles/nanoex.dir/src/performance.cpp.o
.PHONY : src/performance.cpp.o

src/performance.i: src/performance.cpp.i
.PHONY : src/performance.i

# target to preprocess a source file
src/performance.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanoex.dir/build.make CMakeFiles/nanoex.dir/src/performance.cpp.i
.PHONY : src/performance.cpp.i

src/performance.s: src/performance.cpp.s
.PHONY : src/performance.s

# target to generate assembly for a file
src/performance.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanoex.dir/build.make CMakeFiles/nanoex.dir/src/performance.cpp.s
.PHONY : src/performance.cpp.s

src/risk.o: src/risk.cpp.o
.PHONY : src/risk.o

# target to build an object file
src/risk.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanoex.dir/build.make CMakeFiles/nanoex.dir/src/risk.cpp.o
.PHONY : src/risk.cpp.o

src/risk.i: src/risk.cpp.i
.PHONY : src/risk.i

# target to preprocess a source file
src/risk.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanoex.dir/build.make CMakeFiles/nanoex.dir/src/risk.cpp.i
.PHONY : src/risk.cpp.i

src/risk.s: src/risk.cpp.s
.PHONY : src/risk.s

# target to generate assembly for a file
src/risk.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanoex.dir/build.make CMakeFiles/nanoex.dir/src/risk.cpp.s
.PHONY : src/risk.cpp.s

src/strategy.o: src/strategy.cpp.o
.PHONY : src/strategy.o

# target to build an object file
src/strategy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanoex.dir/build.make CMakeFiles/nanoex.dir/src/strategy.cpp.o
.PHONY : src/strategy.cpp.o

src/strategy.i: src/strategy.cpp.i
.PHONY : src/strategy.i

# target to preprocess a source file
src/strategy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanoex.dir/build.make CMakeFiles/nanoex.dir/src/strategy.cpp.i
.PHONY : src/strategy.cpp.i

src/strategy.s: src/strategy.cpp.s
.PHONY : src/strategy.s

# target to generate assembly for a file
src/strategy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanoex.dir/build.make CMakeFiles/nanoex.dir/src/strategy.cpp.s
.PHONY : src/strategy.cpp.s

src/threading.o: src/threading.cpp.o
.PHONY : src/threading.o

# target to build an object file
src/threading.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanoex.dir/build.make CMakeFiles/nanoex.dir/src/threading.cpp.o
.PHONY : src/threading.cpp.o

src/threading.i: src/threading.cpp.i
.PHONY : src/threading.i

# target to preprocess a source file
src/threading.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanoex.dir/build.make CMakeFiles/nanoex.dir/src/threading.cpp.i
.PHONY : src/threading.cpp.i

src/threading.s: src/threading.cpp.s
.PHONY : src/threading.s

# target to generate assembly for a file
src/threading.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanoex.dir/build.make CMakeFiles/nanoex.dir/src/threading.cpp.s
.PHONY : src/threading.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... nanoex_autogen"
	@echo "... nanoex_autogen_timestamp_deps"
	@echo "... nanoex_gui_autogen"
	@echo "... nanoex_gui_autogen_timestamp_deps"
	@echo "... nanoex"
	@echo "... nanoex_gui"
	@echo "... nanoex_autogen/mocs_compilation.o"
	@echo "... nanoex_autogen/mocs_compilation.i"
	@echo "... nanoex_autogen/mocs_compilation.s"
	@echo "... nanoex_gui.o"
	@echo "... nanoex_gui.i"
	@echo "... nanoex_gui.s"
	@echo "... nanoex_gui_autogen/mocs_compilation.o"
	@echo "... nanoex_gui_autogen/mocs_compilation.i"
	@echo "... nanoex_gui_autogen/mocs_compilation.s"
	@echo "... src/chart_widget.o"
	@echo "... src/chart_widget.i"
	@echo "... src/chart_widget.s"
	@echo "... src/indicators.o"
	@echo "... src/indicators.i"
	@echo "... src/indicators.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/market_data.o"
	@echo "... src/market_data.i"
	@echo "... src/market_data.s"
	@echo "... src/matching_engine.o"
	@echo "... src/matching_engine.i"
	@echo "... src/matching_engine.s"
	@echo "... src/order_book.o"
	@echo "... src/order_book.i"
	@echo "... src/order_book.s"
	@echo "... src/performance.o"
	@echo "... src/performance.i"
	@echo "... src/performance.s"
	@echo "... src/risk.o"
	@echo "... src/risk.i"
	@echo "... src/risk.s"
	@echo "... src/strategy.o"
	@echo "... src/strategy.i"
	@echo "... src/strategy.s"
	@echo "... src/threading.o"
	@echo "... src/threading.i"
	@echo "... src/threading.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

